### ISSUE TITLE
Issue of Foreground Service

### ISSUE THREAD

**Issue by ahmadhassan-dev** [oneconnectapi/OneConnectSdk-demo-android#29]
```Error when show notification
android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{1e8c072 9842:com.smithappify.openvpn/u0a197} targetSDK=34
at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
 at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
at android.os.Parcel.readParcelable(Parcel.java:4852)
at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
at android.os.Parcel.createException(Parcel.java:3041)
at android.os.Parcel.readException(Parcel.java:3024)
at android.os.Parcel.readException(Parcel.java:2966)
at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
at android.app.Service.startForeground(Service.java:775)
at top.oneconnectapi.app.core.OpenVPNService.showNotification(OpenVPNService.java:383)
at top.oneconnectapi.app.core.OpenVPNService.onStartCommand(OpenVPNService.java:619)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4821)                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2289)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

I am getting this exception while connecting VPN

**Comment by venusssss** [comment]
这个SDK收费吗？

**Comment by oneconnectapi** [comment]
> ```
> android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{1e8c072 9842:com.smithappify.openvpn/u0a197} targetSDK=34
> at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
> at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
>  at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
> at android.os.Parcel.readParcelable(Parcel.java:4852)
> at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
> at android.os.Parcel.createException(Parcel.java:3041)
> at android.os.Parcel.readException(Parcel.java:3024)
> at android.os.Parcel.readException(Parcel.java:2966)
> at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
> at android.app.Service.startForeground(Service.java:775)
> at top.oneconnectapi.app.core.OpenVPNService.showNotification(OpenVPNService.java:383)
> at top.oneconnectapi.app.core.OpenVPNService.onStartCommand(OpenVPNService.java:619)
> at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4821)                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2289)
> at android.os.Handler.dispatchMessage(Handler.java:106)
> at android.os.Looper.loopOnce(Looper.java:205)
> at android.os.Looper.loop(Looper.java:294)
> at android.app.ActivityThread.main(ActivityThread.java:8177)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
>  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
> ```
> 
> I am getting this exception while connecting VPN

 Kindly contact us via live chat agent , will help you , open our website in right bottom you will see chat icon

**Comment by oneconnectapi** [comment]
> 这个SDK收费吗？

我们有一点点变化，请查看我们的定价 https://developer.oneconnect.top/packages/
